-- Default ice-breaker questions (room_id = NULL → available to every room).
-- ice.js loads .limit(5) when no custom questions exist.
-- 20 generic retro / team-building questions.

INSERT INTO ice_questions (room_id, question_text, option_a, option_b, option_c, option_d, correct_idx, xp_value) VALUES
(NULL, 'What is the primary purpose of a sprint retrospective?',
  'Plan the next sprint backlog',
  'Inspect and adapt the team''s process',
  'Demo finished features to stakeholders',
  'Estimate upcoming stories',
  1, 100),
(NULL, 'Which Agile value is "Individuals and interactions over..."?',
  'Working software',
  'Customer collaboration',
  'Responding to change',
  'Processes and tools',
  3, 100),
(NULL, 'In Scrum, how long is a typical sprint?',
  '1 day',
  '1–4 weeks',
  '3 months',
  '6 months',
  1, 100),
(NULL, 'What does "MVP" stand for in product development?',
  'Most Valuable Player',
  'Minimum Viable Product',
  'Master Version Plan',
  'Multi-Variant Prototype',
  1, 100),
(NULL, 'Which format does the "Start / Stop / Continue" retro use?',
  'Categorise actions into 3 buckets',
  'Rank items by priority',
  'Vote with dots',
  'Draw a sailboat',
  0, 100),
(NULL, 'What is a "WIP limit" in Kanban?',
  'Working-In-Progress token',
  'A max cap on items in a stage',
  'A weekly planning meeting',
  'A customer service metric',
  1, 100),
(NULL, 'Who owns the Product Backlog in Scrum?',
  'Scrum Master',
  'Developers',
  'Product Owner',
  'Stakeholders',
  2, 100),
(NULL, 'What is "velocity" in Agile?',
  'Amount of work a team completes per sprint',
  'Code execution speed',
  'Deployment frequency',
  'Defect rate',
  0, 100),
(NULL, 'The Daily Stand-up should typically last no longer than…',
  '5 minutes',
  '15 minutes',
  '30 minutes',
  '1 hour',
  1, 100),
(NULL, 'Which of these is NOT a Scrum artifact?',
  'Product Backlog',
  'Sprint Backlog',
  'Gantt Chart',
  'Increment',
  2, 100),
(NULL, 'What does "Definition of Done" describe?',
  'The sprint goal',
  'Acceptance criteria for a single story',
  'Shared quality checklist for completed work',
  'Release schedule',
  2, 100),
(NULL, '"Psychological safety" on a team means…',
  'Strong password policies',
  'Members can speak up without fear',
  'Office ergonomics',
  'Clear escalation paths',
  1, 100),
(NULL, 'Which retro technique uses "Mad / Sad / Glad"?',
  'Emotional-seismograph format',
  'Fishbone analysis',
  '5 Whys',
  'Impact mapping',
  0, 100),
(NULL, 'What''s the goal of "blameless" post-mortems?',
  'Identify who to fire',
  'Avoid writing anything down',
  'Focus on system improvements, not individuals',
  'Speed up the meeting',
  2, 100),
(NULL, 'Which metric is a "vanity metric"?',
  'Monthly active users',
  'Raw page views with no context',
  'Conversion rate',
  'Customer retention',
  1, 100),
(NULL, 'In a retro, what is a "dot vote" used for?',
  'Rating individual teammates',
  'Selecting the most important items to discuss',
  'Estimating effort',
  'Logging bugs',
  1, 100),
(NULL, '"Technical debt" most closely means…',
  'Unpaid AWS bills',
  'Hidden costs from suboptimal code shortcuts',
  'Hardware depreciation',
  'Expired SSL certs',
  1, 100),
(NULL, 'Which is a SMART goal attribute?',
  'Scalable',
  'Secret',
  'Specific',
  'Simple',
  2, 100),
(NULL, 'The "Two-Pizza Rule" (Amazon) suggests a team size of…',
  '2–3 people',
  '6–10 people',
  '15–20 people',
  '25+ people',
  1, 100),
(NULL, 'Which of these best describes a "kudos" card in a retro?',
  'A bug report',
  'Positive recognition for a teammate',
  'A feature request',
  'A risk flag',
  1, 100);
